var btn1 = document.getElementById("btn1");
var btn2 = document.getElementById("btn2");
var btn3 = document.getElementById("btn3");
var rvT = document.querySelector('.rvTarjeta');
btn1.addEventListener('click', function () {
    rvT.style.position = "absolute";
    rvT.innerHTML = "<div class=\"rv-tarifarioTrajeta fixed-bottom  mt-3\">\n            <div class=\"rv-contenido shadow-lg sticky-top\" id=\"rvContenido\">\n               <div class=\"row\">\n                   <figure>\n                    <img src=\"./Asset-6.png\" class=\"img-tarjetaBeneficio\" alt=\"\">\n                   </figure>\n                    <div class=\"col\" id=\"contenidoMain\">\n                        <div class=\"row\">\n                            <span class=\"tarjetaTitulo\">Beneficios</span>\n                        </div>\n                        <div class=\"row\">\n                            <span class=\"tarjeta-TituloPaquete\">\n                                P\u00C1GINA COMPLETA\n                            </span>\n                            <p class=\"tarjeta-ContenidoPaquete\">\n                                Un mes de publicidad en nuestra p\u00E1gina web.<br> <br>\n                                Envi\u00F3 de Publicidad a 533,000 empresarios, emprendedores, micro, peque\u00F1a, mediana empresas dentro de Panam\u00E1, influencers, organizaciones y empresas p\u00FAblicas y diplom\u00E1ticos. <br> <br>\n                                Entrevista a propietario o representante que sea asignado por dicha empresa para las pr\u00F3ximas entrevistas de Rendez-Vous Magazine \u2018\u2019El genio detr\u00E1s de la Mar <br> <br>\n                                Tendr\u00E1 conexi\u00F3n directa desde sus anuncios por 30 d\u00EDas (WhatsApp, Instagram, Twitter, Facebook y P\u00E1gina Web). <br> <br>\n                                Los Artes, dise\u00F1os y fotograf\u00EDas deben ser suministradas por el cliente, si el cliente no cuenta con lo solicitado, debe comunicarlo a info@rendezvouscorp.com para asistirle con lo requerido, en este caso tendr\u00EDa un costo adicional. <br> <br>\n                            </p>\n                            <span class=\"tarjeta-TituloPaquete\"> \u00BFDeseas agregar m\u00E1s impacto a tu pauta? </span>\n                            <p class=\"tarjeta-ContenidoPaquete\">\n                                Agrega esto a tu paquete: Producci\u00F3n de 60 segundos, donde humanizaremos tu marca, \n                                documentamos la historia de su creaci\u00F3n y el \u00E9xito que tienen. <br> <br>\n                                Esta producci\u00F3n tiene un costo adicional de $300.00 d\u00F3lares en promoci\u00F3n.</p>\n                        </div>\n                        <div class=\"row mb-2\">\n                            <button class=\"tarjetaContacto\">Contactanos</button>\n                            <button class=\"tarjetaContacto\" id=\"Cerrar\">Cerrar</button>\n                        </div>\n                    </div>\n               </div>\n            </div>\n        </div>";
    var cerrar = document.getElementById('Cerrar');
    cerrar.addEventListener('click', function () {
        rvT.innerHTML = "";
        rvT.style.position = "static";
    });
});
btn2.addEventListener('click', function () {
    rvT.style.position = "absolute";
    rvT.innerHTML = "<div class=\"rv-tarifarioTrajeta fixed-bottom  mt-3\">\n                <div class=\"rv-contenido shadow-lg sticky-top\" id=\"rvContenido\">\n                   <div class=\"row\">\n                       <figure>\n                        <img src=\"./Asset-6.png\" class=\"img-tarjetaBeneficio\" alt=\"\">\n                       </figure>\n                        <div class=\"col\" id=\"contenidoMain\">\n                            <div class=\"row\">\n                                <span class=\"tarjetaTitulo\">Beneficios</span>\n                            </div>\n                            <div class=\"row\">\n                                <span class=\"tarjeta-TituloPaquete\">\n                                    MEDIA P\u00C1GINA\n                                </span>\n                                <p class=\"tarjeta-ContenidoPaquete mt-2\">\n                                    15 d\u00EDas en nuestro espacio de publicidad de nuestra p\u00E1gina web en todas las categor\u00EDas <br> <br>\n                                    Envi\u00F3 de Publicidad a 533,000 empresarios, emprendedores, micro, peque\u00F1a, mediana empresas dentro de Panam\u00E1, influencers, organizaciones y empresas p\u00FAblicas y diplom\u00E1ticos. <br> <br>\n                                    Tendr\u00E1 conexi\u00F3n directa desde sus anuncios por 15 d\u00EDas (WhatsApp, Instagram). <br> <br>\n                                    Los Artes, dise\u00F1os y fotograf\u00EDas deben ser suministradas por el cliente, si el cliente no cuenta con lo solicitado, debe comunicarlo a info@rendezvouscorp.com para asistirle con lo requerido, en este caso tendr\u00EDa un costo adicional. <br> <br>\n                                </p>\n                                <span class=\"tarjeta-TituloPaquete\"> \u00BFDeseas agregar m\u00E1s impacto a tu pauta? </span>\n                                <p class=\"tarjeta-ContenidoPaquete mt-2\">\n                                    Agrega esto a tu paquete: Producci\u00F3n de 60 segundos, donde humanizaremos tu marca, \n                                    documentamos la historia de su creaci\u00F3n y el \u00E9xito que tienen. <br> <br>\n                                    Esta producci\u00F3n tiene un costo adicional de $300.00 d\u00F3lares en promoci\u00F3n.</p>\n                            </div>\n                            <div class=\"row mb-5 mt-2\">\n                                <button class=\"tarjetaContacto\">Contactanos</button>\n                                <button class=\"tarjetaContacto\" id=\"Cerrar\">Cerrar</button>\n                            </div>\n                        </div>\n                   </div>\n                </div>\n            </div>";
    var cerrar = document.getElementById('Cerrar');
    cerrar.addEventListener('click', function () {
        rvT.innerHTML = "";
        rvT.style.position = "static";
    });
});
btn3.addEventListener('click', function () {
    rvT.style.position = "absolute";
    rvT.innerHTML = "<div class=\"rv-tarifarioTrajeta fixed-bottom  mt-3\">\n                <div class=\"rv-contenido shadow-lg sticky-top\" id=\"rvContenido\">\n                   <div class=\"row\">\n                       <figure>\n                        <img src=\"./Asset-6.png\" class=\"img-tarjetaBeneficio\" alt=\"\">\n                       </figure>\n                        <div class=\"col\" id=\"contenidoMain\">\n                            <div class=\"row\">\n                                <span class=\"tarjetaTitulo\">Beneficios</span>\n                            </div>\n                            <div class=\"row\">\n                                <span class=\"tarjeta-TituloPaquete\">\n                                    CINTILLO PARA EMPRENDEDORES\n                                </span>\n                                <p class=\"tarjeta-ContenidoPaquete mt-2\">\n                                    Cintillo en nuestra edici\u00F3n de Revista <br> <br>\n                                    7 d\u00EDas en nuestro espacio de publicidad de nuestra p\u00E1gina web en todas las categor\u00EDas <br> <br>\n                                    Tendr\u00E1 conexi\u00F3n directa desde sus anuncios por 7 d\u00EDas (Instagram)<br> <br>\n                                    Los Artes, dise\u00F1os y fotograf\u00EDas deben ser suministradas por el cliente, si el cliente no cuenta con lo solicitado, debe comunicarlo a info@rendezvouscorp.com para asistirle con lo requerido, en este caso tendr\u00EDa un costo adicional. <br> <br>\n                                </p>\n                                <span class=\"tarjeta-TituloPaquete\"> \u00BFDeseas agregar m\u00E1s impacto a tu pauta? </span>\n                                <p class=\"tarjeta-ContenidoPaquete mt-2\">\n                                    Agrega esto a tu paquete: Producci\u00F3n de 60 segundos, donde humanizaremos tu marca, \n                                    documentamos la historia de su creaci\u00F3n y el \u00E9xito que tienen. <br> <br>\n                                    Esta producci\u00F3n tiene un costo adicional de $300.00 d\u00F3lares en promoci\u00F3n.</p>\n                            </div>\n                            <div class=\"row mb-5 mt-2\">\n                                <button class=\"tarjetaContacto\">Contactanos</button>\n                                <button class=\"tarjetaContacto\" id=\"Cerrar\">Cerrar</button>\n                            </div>\n                        </div>\n                   </div>\n                </div>\n            </div>";
    var cerrar = document.getElementById('Cerrar');
    cerrar.addEventListener('click', function () {
        rvT.innerHTML = "";
        rvT.style.position = "static";
    });
});
